var dictionary = [ 
'abased',
'above',
'angled',
'annulet',
'arched',
'argent',
'armed',
'arrondi',
'azure',
'bar gemel',
'bar',
'barry bendy',
'barry indented one in the other',
'barry pily',
'barry',
'base',
'battled embattled',
'battled',
'below',
'bend couped',
'bend voided',
'bend',
'bendlet',
'bendwise',
'bendy',
'between',
'bevilled',
'bordure',
'botonny',
'braced',
'brunatre',
'canadian pale',
'canton',
'carnation',
'celestial azure',
'chape',
'charged',
'chausse',
'chevron burst',
'chevron couched',
'chevron disjointed',
'chevron fracted',
'chevron removed',
'chevron rompu',
'chevron',
'chevronel',
'chevronny',
'chief couped',
'chief',
'cinquefoil',
'closet',
'compony',
'cotticed',
'couchant',
'counter',
'couped',
'courant',
'crancelin',
'crescent',
'cross formy',
'cross parted fretty',
'cross pierced',
'cross tripartite fretty',
'crown',
'dance',
'dancetty floretty',
'dancetty',
'depressed',
'dexter',
'dormant',
'double arched',
'dovetailed',
'drawn',
'effect',
'embattled arrondi',
'embattled brettessy',
'embattled counter-embattled',
'embattled',
'enarched',
'endorse',
'engrailed',
'enhanced',
'enty in point',
'erect',
'ermine',
'ermines',
'erminites',
'erminois',
'escallop',
'escartelly',
'escutcheon',
'fess between 2 chevrons',
'fess couped',
'fess voided',
'fess',
'fillet cross',
'fillet',
'fir tree topped',
'fir twigged',
'flank',
'flaunch',
'floretty',
'flory',
'ford',
'fracted',
'fret couped',
'fret',
'fretty',
'fusily bendy',
'fusily',
'gemel',
'gore',
'gorge',
'graft',
'gules',
'gusset',
'gyron',
'gyronny of 10',
'gyronny of 12',
'gyronny of 14',
'gyronny of 16',
'gyronny of 6',
'gyronny of 8',
'gyronny',
'head',
'honour',
'humet',
'in pale',
'in point',
'indented pommetty',
'indented',
'inescutcheon',
'inflamed',
'invected',
'jelloped',
'label',
'larger',
'leaved',
'lion',
'lowered',
'lozenge',
'lozengy',
'martlett',
'murrey',
'natural',
'nebuly',
'nombril',
'nowy',
'of the field',
'of the first',
'of the last',
'of the second',
'of the third',
'orle',
'overall',
'pale voided',
'pale',
'palet',
'pall',
'paly bendy',
'paly',
'passant',
'pean',
'pellet',
'per bend',
'per chevron',
'per fess',
'per pale',
'per pall arrondi',
'per pall',
'per pile',
'per saltire',
'pile embowed',
'pile',
'pily bendy',
'pily',
'plain cross',
'plate',
'point dexter',
'point in point',
'point sinister',
'point',
'potent',
'potenty',
'purpure',
'quarter',
'quartered',
'quarterly',
'quatrefoil',
'raguly',
'raised',
'rampant',
'rayonny',
'reversed',
'ribbon',
'rose',
'sable',
'saltire',
'sanguine',
'sexfoil',
'shakefork',
'shown',
'sinister',
'smaller',
'square flaunch',
'stag',
'statant',
'style',
'sword',
'thorny',
'throughout',
'tierce',
'tierced in bend',
'tierced in chevron',
'tierced in fess',
'tierced in pale',
'tierced',
'tinctures',
'torteau',
'trefle counter trefle',
'tressure',
'trimount',
'urdy',
'using',
'vair',
'vert',
'voided',
'wavy',
'with',
'within',
];

// Register our custom Codemirror hint plugin.
CodeMirror.registerHelper('hint', 'blazonHint', function(editor) {
    var cur = editor.getCursor(),
        curLine = editor.getLine(cur.line);
    var start = cur.ch,
        end = start;
    while (end < curLine.length && /[\w$]+/.test(curLine.charAt(end))) ++end;
    while (start && /[\w$]+/.test(curLine.charAt(start - 1))) --start;
    var curWord = start != end && curLine.slice(start, end);
    var regex = new RegExp('^' + curWord, 'i');
    return {
        list: (!curWord ? [] : dictionary.filter(function(item) {
            return item.match(regex);
        })).sort(),
        from: CodeMirror.Pos(cur.line, start),
        to: CodeMirror.Pos(cur.line, end)
    }
});

CodeMirror.commands.autocomplete = function(cm) {
    CodeMirror.showHint(cm, CodeMirror.hint.blazonHint);
};