var normalisations = [
    ["\\-",' '],
    [";"," "],
    [":"," "],
    [","," "],
    ["\\."," "],
//	['à','a'],
    ["À","à"],
   // ['á','a'],
   // ['ô','o'],
   // ['â','a'],
  //  ['è','e'],
//	['é','e'],
 //   ['ê','e'],
    ['É','é'],
    ['È','è'],
 //   ['ç','c'],
    ['û','u'],
    ['î','i'],
    ['°','e'],
    ["l'","l "], // bit of a cheat
    ["L'","l "],
    ["d'","d "],
    ["D'","d "],
];


var lexicon = [
    ["1","1"],
    ["1er?","1st"],
    ["2","2"],
    ["2e","2nd"],
    ["3","3"],
    ["3e","3rd"],
    ["4","4"],
    ["4e","4th"],
    ["5","5"],
    ["6","6"],
    ["à dextre","to the dexter"],
    ["à deux","two"],
    ["à douze","twelve"],
    ["à l extérieur","on the outside"],
    ["à la bordure","a bordure"],
    ["à la fasce","a fess"],
    ["à la bande","a bend"],
    ["à quatre","four"],
    ["à plomb","merlons in pale [vertically]"],
    ["à senestre","to the sinister"],
    ["à trois","three"],
    ["à","with/to"],
    ["a","a)"],
    ["abaissée?s?","abased [lower than normal]/lowered"],
    ["abeilles?","bee"],
    ["abîme","fess point"],
    ["aboutée?s?","conjoined"],
    ["acc de","accompanied by"],
    ["accompagné de","accompanied by"],
    ["acc","accompanied by"],
    ["accolée?s? de?","accompanied by"],
    ["accornée?s?","horned"],
    ["accostant","either side of"],
    ["accostée?s? de","having to the sides/surrounded by"],
    ["accostée?s?","side by side"],
    ["accroupi","sejant"],
    ["acculée?s?","rampant/back to back"],
    ["add?ossée?s?","addorsed [back to back]"],
    ["adextrée?s?","having to the dexter"],
    ["affaisée?s?","bending downwards"],
    ["affrontée?s?","affrontant [face to face]"],
    ["affutée?s?","trunked/[gun] carraige"],
    ["agitée?s?","with curling waves"],
    ["agneau pascal","paschal lamb"],
    ["agneaus?","lamb"],
    ["aigles?","eagle"],
    ["aigrette","egret [small heron]"],
    ["aigrettes","egrets [small herons]"],
    ["aiguiére","ewer [?]"],
    ["aiguisée?s?","fitchy at the foot"],
    ["ailée?s?","winged"],
    ["ailes?","wing"],
    ["aires?","nest"],
    ["ajourée?s?","openings"],
    ["alcyon","alcyon [swan-like mythical bird]"],
    ["alérions","eaglets [without beaks or legs]"],
    ["al[eé]?sée?s?","couped"],
    ["alias","alternatively"],
    ["allumée?s?","aflame"],
    ["alouettes?","skylark"],
    ["alternant","alternatively"],
    ["alternativement","alternately"],
    ["amphitere","amphitere [winged serpent]"],
    ["anchée?s?","curved"],
    ["ancres?","anchor"],
    ["ancrée?s?","cercele"],
    ["ânes?","donkey"],
    ["anges?","angel"],
    ["anglée?s?","rayed at the angles [?]"],
    ["angons?","spear head"],
    ["anilles?","mill rind"],
    ["animée?s?","eyes"],
    ["annelets?","annulet"],
    ["anneaux?","rings"],
    ["appaumée?s?","with open palm"],
    ["appointée?s?","touching at the point"],
    ["appuyée?s? sur","resting on"],
    ["appuyant","resting"],
    ["aquilon","north wind"],
    ["arbalète","crossbow"],
    ["arbres?","tree"],
    ["arche de noe","Noah's Ark"],
    ["arcs?","bow"],
    ["arches","arches"],
    ["arche","arch"],
    ["archieres?","arrow slit"],
    ["arctée?s?","embowed"],
    ["ardente?s?","glowing"],
    ["argent","argent"],
    ["armé de toutes pièces","fully armoured"],
    ["armée?s?","armed/armoured"],
    ["armes?","coat of arms"],
    ["arrachée?s?","eradicated"],
    ["arrêtée?s?","statant"],
    ["arrondie?","circular/circled"],
    ["assis","sejant"],
    ["attachée?s?","attached"],
    ["aquilons?","north wind [infant face blowing]"],
    ["au 1","1st"],
    ["au 2","2nd"],
    ["au 3","3rd"],
    ["au 4","4th"],
    ["au 5","5th"],
    ["au 6","6th"],
    ["au canton","a canton"],
    ["au centrée?s?","at the centre"],
    ["au chef","a chief"],
    ["au chevron","a chevron"],
    ["au desso?us","above"],
    ["au naturel","proper"],
    ["au pal","a pale"],
    ["au rabat","with flaps"],
    ["au rosier","a rose bush"],
    ["au sautoir","a saltire"],
    ["au sommet","from the summit/to the summit"],
    ["aux?quell?e?s?","of which"],
    ["aussi","also"],
    ["autel","altar"],
    ["autr[ée]?s?","other"],
    ["aux 1 et 4","1st and 4th"],
    ["aux 2 et 3","2nd and 3rd"],
    ["aux armes du","with the arms of"],
    ["aux armes","with the arms of"],
    ["aux?","of/a/an"],
    ["autruches?","ostrich"],
    ["avant bras","fore-arms"],
    ["avant mur","fore-wall"],
    ["avec","with"],
    ["ayante?s?","having"],
    ["azur","azure"],
    ["b","b)"],
    ["baillonnée?s?","holding a baton in its jaws"],
    ["baissée?s?","lowered"],
    ["balance","set of scales"],
    ["bandée?s?","bendy"],
    ["bande","bend"],
    ["banderoles?","narrow flag"],
    ["bandes?","bendlets"],
    ["bannetons?","fish trap"],
    ["bannerets?","small flag"],
    ["bannieres?","square flag"],
    ["bagues?"," [jewellery] ring"],
    ["bars?","[fish] barbel"],
    ["barbée?s?","barbed/jelloped"],
    ["barbue?s?","bearded"],
    ["bardée?s?","wearing horse armour"],
    ["barillets?","small barrels"],
    ["barre","bend sinister"],
    ["barrée?","bendy sinister"],
    ["barres","bendlets sinister"],
    ["basilic","basilisk"],
    ["bâtons?","[ragged staff] baton"],
    ["bastillée?s?","embattled on the lower edge"],
    ["bassinets?","steel helmet"],
    ["bataillée?s?","clapper [of the bell]"],
    ["baton","baton"],
    ["baudrier","baldric [sword belt]"],
    ["becs?","nibs/beaks"],
    ["becquée?s?","beaked"],
    ["béliers?","ram/battering ram"],
    ["besant torteau","roundel of two tinctures"],
    ["besantée?s?","bezanty"],
    ["besants?","bezant"],
    ["bigarrée?s?","winged"],
    ["billetée?s?","billetty"],
    ["billettes?","billet"],
    ["bisse","nowed"],
    ["bocquets?","pike head"],
    ["boeuf","ox [with tail pendant]"],
    ["boeufs","oxen [with tails pendant]"],
    ["boutons?","bud"],
    ["bonnets? albanais","Albanian [woollen?] hat"],
    ["bonnet","hat"],
    ["bords?","edge"],
    ["bordée?s?","fimbriated/with a bordure"],
    ["bordure","bordure"],
    ["bottée?s?","booted"],
    ["boucs?","goat"],
    ["bouclée?s?","buckled"],
    ["boule?","ball"],
    ["boules","balls"],
    ["bouquet","bouquet"],
    ["bouquetins?","ibex"],
    ["bourdon de pelerin","pilgrim's staff"],
    ["bourdons?","staff"],
    ["bourdonnée?s?","pommetty"],
    ["bourlet","wreath on the helmet"],
    ["bouses?","water bouget"],
    ["bout","tip/end/point"],
    ["bouts","tips/ends/points"],
    ["bouterolle","scabbard end"],
    ["bouterolles","ends of the scabbards"],
    ["boutoirs?","[of the boar] snout"],
    ["boutonnée?s?","budded/buttoned"],
    ["branchée?s?","branched"],
    ["branches?","branch"],
    ["brandissant","brandishing"],
    ["bras","arm"],
    ["brebis","grazing sheep"],
    ["bretessée?s?","embattled [on both sides]"],
    ["bridée?s?","bridled"],
    ["bris d huis","hinge [of door]"],
    ["brisée?s?","broken"],
    ["brochant","covering"],
    ["broyes","hemp brake"],
    ["brunatre","brunatre"],
    ["buffle","ox head [with ring in nostrils]"],
    ["burelée?s?","barry"],
    ["bureles?","barrulet"],
    ["buste?","bust"],
    ["cablée?s?","wreathed"],
    ["cabochée?s?","caboshed [cut off at neck]"],
    ["cabrée?s?","on its haunches"],
    ["cadenas","padlock"],
    ["caducees?","rod of Mercury"],
    ["calatrava","calatrava"],
    ["canettes?","[without beak or feet] duck"],
    ["cannelée?s?","invected"],
    ["cantons?","quarter"],
    ["cantonnée?s?","having in each quarter"],
    ["capuchons?","hood"],
    ["carnation","carnation"],
    ["carre","square"],
    ["carreaux","cushions"],
    ["casque couronné","Crowned with a helmet"],
    ["casques?","helmet"],
    ["castors?","beaver"],
    ["caudée?s?","tailed"],
    ["cavaliers?","cavalier"],
    ["ceinte?s?","belted"],
    ["ceintures?","belt"],
    ["ceintrée?s?","arched/banded"],
    ["celle","that"],
    ["celui du 1","that of the 1st"],
    ["celui d[ue]s? 3","that of the 3rd"],
    ["cep de vigne","vine shoot"],
    ["ceps de vigne","vine shoots"],
    ["ceps","handcuffs"],
    ["cerfs?","stag"],
    ["ce(s|tte)","this/these"],
    ["ce(lui|la|lles)","that of the/those of the"],
    ["ch de","charged with"],
    ["ch","charged with/charged"],
    ["chabots?"," [fish] chub"],
    ["chacune?","each/each having"],
    ["chaine","chain"],
    ["chainons","[chain] links"],
    ["chamois","mountain goat"],
    ["champs?","field"],
    ["chantant","crowing"],
    ["chapalet","wreath/rosary"],
    ["chapalets","wreaths/rosaries"],
    ["chape chaussée?s?","chape chause [division top centre to dex & sin base]"],
    ["chapé ployée?s?","chape ploye [division top centre curved to dex & sin base]"],
    ["chape","chape"],
    ["chapeaux? de tournois?", "tournament [tilting] helm"],
    ["chapeaux? piramidale?s?","pointed hat"],
    ["chapeaux? albanais","woollen hat"],
    ["chapeau","hat"],
    ["chaperons?","hood"],
    ["chaperonnée?s?","wearing a hood"],
    ["chaque","each"],
    ["chargée?s? d une?","charged with a"],
    ["chargée?s? de","charged with"], // check first
    ["chargée?s?","charged"], // check after
    ["chargée?s? de la devise","with the motto"],
    ["chateau","castle"],
    ["chatelée?s?","semy de castles"],
    ["chatonée?s?","sparkling with"],
    ["chaudières?","cauldron"],
    ["chaussé?e? trapp?es?","caltrap"],
    ["chaussé?e? ployée?s?","chausse ploye [division curved from middle base to dex & sin top]"],
    ["chaussé?e?","chausse [division from middle base to top dex & sin]"],
    ["chaussetrapes?","caltrap"],
    ["chauve souris","bat"],
    ["chef chevron","chief combined with chevron"],
    ["chef de france","chief azure charged with three fleur-de-lys or"],
    ["chef de l empire","chief or charged with an eagle displayed sable"],
    ["chef dextre","chief in dexter only [line from top sinister to middle dex flank]"],
    ["chef pale","chief combined with pale"],
    ["chef senestre","chief in sinister only [line from top dexter to middle sin flank]"],
    ["chef voute","chief enarched"],
    ["chef","chief"],
    ["chemin","pathway/roadway"],
    ["chênes?","oak"],
    ["cherubins","angel heads conjoined"],
    ["cheval","horse"],
    ["cheval bai","bay horse"],
    ["chevaliers?","knight"],
    ["chevelée?s?","hair"],
    ["cheveux","hair"],
    ["chevaux","horses"],
    ["chevillée?s?","having points [on the antlers]"],
    ["chevreuils?","roe deer"],
    ["chevrons?","chevron"],
    ["chevronnée?s?","chevronny"],
    ["chicots","rag?ged staff"],
    ["chiens de chasse","hunting dogs"],
    ["chiens?","dog"],
    ["chiffre","figure"],
    ["chimeres?","chimera"],
    ["choucas","cornish chough"],
    ["chouettes?","owl"],
    ["cimier","Crest:"],
    ["cimiers","Crests:"],
    ["cinq","five"],
    ["cigognes?","stork"],
    ["cintrée?s?","banded"],
    ["clairevoies","spaces [within the trellis]"],
    ["claricords?","clarion"],
    ["clarinée?s?","belled"],
    ["clés?","key"],
    ["clouée?s?","nailed"],
    ["cloches?","bell"],
    ["clocher","bell tower"],
    ["clous de la passion","nails of the cross [square heads]"],
    ["coiffée? d une?","wearing on the head a"],
    ["collett?ée?s?","collared"],
    ["collines?","hill"],
    ["colombe?","dove"],
    ["colombes","doves"],
    ["colonnes?","column"],
    ["col rabattu","shoulder flaps [epaulets?]"],
    ["cols?","shoulder"],
    ["comble","demi-chief [half normal height]"],
    ["comèté?e?s?","comet"],
    ["compon","piece of the compony"],
    ["componn?ée?s?","compony"],
    ["conduisante?s?","heading towards"],
    ["confa[ln]on","banner [church]"],
    ["conformes aux","conforming to the [same as]"],
    ["conque marine","conch shell"],
    ["contournée?s?","reversed"],
    ["contre appaumée?s?","showing the back"],
    ["contre bande","bendy counterchanged"],
    ["contre barre","bendy sinister counterchanged"],
    ["contre bretessée?s?","counter embattled [on both sides offset]"],
    ["contre chevronne","chevronny counterchanged"],
    ["contre compony","counter compony"],
    ["contre ecartele","counter quartered"],
    ["contre ecotée?s?","counter[?] raguly"],
    ["contre fasce","barry counterchanged"],
    ["contre flambant","inflamed both sides"],
    ["contre fleurée?s?","flory counter flory"],
    ["contre hermine","counter ermine"],
    ["contre pal[ey]","paly counterchanged"],
    ["contre passante?s?","palewise opposite [directions]"],
    ["contre vair","counter vair"],
    ["contre vaire","counter vairy"],
    ["contre?s?","against"],
    ["coqs?","cockerel"],
    ["coquerelles","three filberts in cups [one in pale two fesswise]"],
    ["coques?","shell"],
    ["coquillage","conch shell"],
    ["coquilles?","escallop"],
    ["cordée?s?","stringed"],
    ["cordelierée?s?","surrounded by a knotted cord"],
    ["cormorans?","cormorant"],
    ["corneilles?","crow"],
    ["cors? de chasse","hunting horns"],
    ["cors?","horn"],
    ["cornes? de buffle","buffalo horns"],
    ["cornes?","horn"],
    ["cornieres?","handle [of the cauldron]"],
    ["côtés?","side"],
    ["cotice en barre","bendlet sinister"],
    ["coticées?","bendy/cotticed"],
    ["cotice","bendlet"],
    ["cotices","bendlets"],
    ["cotoyée?s?","surrounded [with the same orientation] by"],
    ["cotte d armes","chainmail coat"],
    ["couard","coward"],
    ["couch(ant)?e?es?","couchant [sitting down]"],
    ["couchée?s?","laying on the ground/on its side/on their side"],
    ["coeurs?","heart"],
    ["coude","elbow"],
    ["couleuvre","serpent [with undulating body]"],
    ["coulissée?s?","portcullis"],
    ["countourne","reversed [turned to face sinister]"],
    ["coupe couverte","covered cup"],
    ["coupeaux","peaks"],
    ["coupée?s?","per fess/couped"],
    ["le coupé","the partition"],
    ["coupes couvertes","covered cups"],
    ["couple de chiens","two dogs leashed"],
    ["couples","tied together"],
    ["courante?s?","courant [running]"],
    ["courbée?s?","curved"],
    ["courbes?","curve"],
    ["corbeaux?","crow"],
    ["couronnes? royales?","Royal crown"],
    ["couronnes? murales?","mural crown"],
    ["couronnes? ducales?","ducal crown"],
    ["couronnée?s?","crowned"],
    ["couronnes?","crown"],
    ["courtine","curtain wall"],
    ["cousu","[stitched to the adjacent colour]"],
    ["couverte?s?","covered by"],
    ["crampons?"," [double ended] hook"],
    ["crancelin","curved bend like a coronet on upper edge"],
    ["cranes?","heads"],
    ["crêtée?s?","crested"],
    ["cremaillieres?","ratchet hook [to support a cauldron]"],
    ["créneaux","merlons"],
    ["crénell?ée?s?","embattled on the upper side"],
    ["crequiers?","wild cherry tree"],
    ["cretée?s?","crested"],
    ["cri de guerre","motto"],
    ["crinée?s?","hair"],
    ["croc(het)?s?","hook"],
    ["croisée?s?","charged with a cross"],
    ["croissants?","crescent"],
    ["croiss?ettes?","crosslet"],
    ["croix calvaire","calvary cross"],
    ["croix grecque","greek cross"],
    ["croix latine","latin cross"],
    ["croix","cross"],
    ["cubes?","cube"],
    ["cuillers?","spoon"],
    ["cuirassés?","breastplate"],
    ["cupole","dome"],
    ["cyclamor","orle"],
    ["cygnes?","swan"],
    ["d argent","argent"],
    ["d armes?","of arms"],
    ["d azur","azure"],
    ["d épines", "of thorns"],
    ["d homme","of a man"],
    ["d intersection","of the intersection"],
    ["d or","or"],
    ["d une?","{article}"],
    ["d un écusson","with an escutcheon"],
    ["d un surtout","a coat"],
    ["d une? autre","another"],
    ["d une?","a/an/the/of a/of the/from a"],
    ["daim","deer [like stag but wider antlers]"],
    ["dalmatiques?","angel's tunic"],
    ["dans le sens de la barre","bendwise sinister"],
    ["dans des joncs","in some rushes"],
    ["dans","in"],
    ["dauphins?","dolphin"],
    ["dés?","dice"],
    ["de couleur brunâtre","brunatre"],
    ["de carnation","carnation"],
    ["de derriere","behind/the rear"],
    ["de devant","the front/in front"],
    ["de face","facing forwards"],
    ["de femme","of a man"],
    ["de fer","of iron"],
    ["de front","facing forwards"],
    ["de gueules","gules"],
    ["de l un à l autre","counterchanged"],
    ["de l un en l autre","counterchanged"],
    ["de laquell?e?s?","of which"],
    ["de milieu","of the centre"],
    ["de profil","in profile"],
    ["de purpure","purpure"],
    ["de sable","sable"],
    ["de ses pattes","in its paws"],
    ["de sinople","vert"],
    ["de son","in its"],
    ["de toute?s? pieces","fully"],
    ["de vair","vair"],
    ["decapitée?s?","without the head"],
    ["déesse","goddess"],
    ["défaillante?s?","missing/broken"],
    ["défendue?s?","tusked"],
    ["dégouttant de sang","dripping blood"],
    ["dejoint","rompu [broken]"],
    ["démanchée?s?","without handle"],
    ["démembrée?s?","without legs"],
    ["demi aigle","demi eagle"],
    ["demi ramures?","antler"],
    ["demi vols?","single wing"],
    ["demi","demi"],
    ["demies","halves"],
    ["denchée?s?","indented"],
    ["dentelée?s?","indented [on one edge]"],
    ["denchure","fillet indented in chief"],
    ["dents?","teeth"],
    ["dépouillée?s?","skinned"],
    ["derriere","behind"],
    ["des mots","the words"],
    ["des mes?mes?", "the same"],
    ["de?s?","of/from/in/by/the/of the/of a/of an/with"],
    ["désarmée?s?","disarmed"],
    ["deux casques couronnés","Crowned with two helmets"],
    ["deux","two"],
    ["devant","in front of"],
    ["dextre","dexter"],
    ["dextrochère","right arm"],
    ["dextrocheres","right arms"],
    ["devise","Motto:"],
    ["diadémée?s?","haloed"],
    ["diamantée?s?","diamonds [faceted]"],
    ["diaprée?s?","diapered"],
    ["diffamée?s?","tailless"],
    ["diminuée?s?","smaller"],
    ["dirigée?s?","directed"],
    ["disposée?s?","arranged"],
    ["divise en chevron","per chevron"],
    ["divise","barrulet in chief"],
    ["division","division"],
    ["dix","ten"],
    ["dolce","fox [italian]"],
    ["doigts?","fingers"],
    ["doloires?","broad axe"],
    ["donjons?","turret"],
    ["donjonnée?s?","turreted"],
    ["dorée?s?","gilded"],
    ["dos","back"],
    ["doublets?","gnats"],
    ["doublé","lined"],
    ["dragon monstreux","dragon [with human head bearded with serpents]"],
    ["dragon","wyvern/dragon"],
    ["dragonnée?s?","with a dragon's tail"],
    ["dragons","wyverns"],
    ["drapeau","flag"],
    ["drapeaux","flags"],
    ["dressée?s?","upright"],
    ["du 1","of the 1st"],
    ["du 2","of the 2nd"],
    ["du 3","of the 3rd"],
    ["du 4","of the 4th"],
    ["du bas","from the base"],
    ["du champ","of the field"],
    ["du chef","from the chief"],
    ["du coupe","from the partition [fess]"],
    ["du dernier","of the last"],
    ["du fasce","from the fess"],
    ["du flanc","from the flank"],
    ["du mes?me","of the same"],
    ["du même","of the same"],
    ["du milieu","of the middle"],
    ["du parti","from the partition [pale]"],
    ["du premier","of the first"],
    ["du second","of the second"],
    ["du troisieme","of the third"],
    ["du","of/from/the/of the"],
    ["ducs?","small owl"],
    ["eaux?","river/water"],
    ["ébranchée?s?","without branches"],
    ["écaillée?s?","scaled"],
    ["écartelé en sautoir","quarterly per saltire"],
    ["écartelée?","quarterly"],
    ["écartelures","quarterings"],
    ["échancrée?s?","engrailed [but wider and deeper]"],
    ["échelles? d escalade","scaling ladders"],
    ["échelles?","ladder"],
    ["échiquetée?s?","checky"],
    ["écimée?s?","top [of the chevron] cut flat"],
    ["éclatée?s?","splintered"],
    ["écorchée?s?","paws gules"],
    ["écot","tree branch"],
    ["écotée?s?","raguly"],
    ["écran","fan shaped crest [german]"],
    ["écrevisses?","crayfish"],
    ["écussons?","escucheon"],
    ["écu","shield"],
    ["effarouchée?s?","rampant"],
    ["effeuillée?s?","leafless"],
    ["église","church"],
    ["élancée?s?","springing forward"],
    ["élevante?s?","raised"],
    ["émail","colour"],
    ["émanche","pily"],
    ["émanchure","triangle [of the chape]"],
    ["émauxs?","colours"],
    ["embouche","mouthpiece"],
    ["embouchure","mouthpiece"],
    ["embouchures","mouth"],
    ["emboutée?s?","at the end [tip]"],
    ["embrasse","per chevron [from the flanks]"],
    ["emmanchée?s?","handle"],
    ["emmuselée?s?","muzzled"],
    ["embrassant","embraced [surrounded] by"],
    ["émoussée?s?","blunted"],
    ["empennée?s?","flighted [of arrows]"],
    ["empietante?s?","holding in its talons"],
    ["empoignante?s?","holding in its fist"],
    ["emsemblée?s?","between them"],
    ["en (son|sa) bec","in its beak"],
    ["en bande","bendwise/in bend"],
    ["en banniere","in an escutcheon"],
    ["en barre","bendwise sinister/in bend sinister"],
    ["en barroquée?s?","emerging from behind the shield"],
    ["en bas","downwards"],
    ["en chef","in chief"],
    ["en coeur","in the centre"],
    ["en croix","in cross"],
    ["en demi cercle","in a semi circle"],
    ["en fasces?","fesswise/in fess"],
    ["en flancs?","in the flanks"],
    ["en forme","in the form of/couchant [hare]"],
    ["en haute?s?","upwards"],
    ["en orle","in orle"],
    ["en pairle","en pall"],
    ["en pale?s?","palewise"],
    ["en pointe","in base"],
    ["en sautoir","saltirewise"],
    ["enflammée?s?","inflamed"],
    ["en","in"],
    ["enchainée?s?","chained"],
    ["enchaussures?","triangle [of the chausse]"],
    ["enclavée?s?","intruding"],
    ["enclose?s?","enclosed by"],
    ["enclumes?","anvil"],
    ["encochée?s?","cocked [of a bow and arrow]"],
    ["enfilant","piercing"],
    ["englantée?s?","acorned"],
    ["engoulante?s?","swallowing"],
    ["engoulée?s?","being swallowed by"],
    ["engrelée?s?","engrailed"],
    ["enguichée?s?","rimmed with metal"],
    ["ensanglantée?s?","stained with blood"],
    ["ensemble","together"],
    ["entée?s?","nebuly"],
    ["entouré","entirely within"],
    ["entrelacée?s","interlaced"],
    ["entravaillée?s?","interlaced"],
    ["entre","between"],
    ["entretenus","interlaced [keys]"],
    ["environned","encircled"],
    ["éole","symbol of the wind"],
    ["épanouie?s?","opened [expanded]"],
    ["épars","wild"],
    ["épaules?","shoulder"],
    ["épées?","sword"],
    ["éperons?","spur"],
    ["épis?","tuft"],
    ["éployée?s?","displayed"],
    ["équerres?","carpenters square"],
    ["équipée?s?","rigged"],
    ["équipolle","checky [large]"],
    ["escarboucles?","carbuncle"],
    ["escarres?","filet [small]"],
    ["essonier","tressure"],
    ["estomac","chest"],
    ["essoranté?e?s?","soaring"],
    ["essorée?s?","roofed [pointed]"],
    ["est","is"],
    ["estacades?","palisade"],
    ["estayes?","chevronel"],
    ["estocs?","ragged staff"],
    ["et","and"],
    ["étages?","level"],
    ["étais?","chevronel"],
    ["étetée?s?","headless"],
    ["étendue?s?","extended"],
    ["etincelante?s?","sparkling"],
    ["étoiles?","etoile"],
    ["évasée?s?","voided"],
    ["évidée?s?","voided"],
    ["éxterieurée?s?","on the outside"],
    ["failli","fractured"],
    ["faucilles?","sickle"],
    ["falots?","torch/fire grate"],
    ["fanals?","beacon"],
    ["fasce","fess"],
    ["fascée?s?","barry"],
    ["fascée contre fascée","per pale and barry counterchanged"],
    ["fasces","bars"],
    ["faisceaux?","bundle"],
    ["faux écu","escutcheon with bordure"],
    ["faux","scythe"],
    ["femme","woman"],
    ["fendus?","split"],
    ["fers? à cheval?","horseshoe"],
    ["fers? de moulin","mill rind"],
    ["fermails?","buckle"],
    ["fermée?s?","closed"],
    ["feuillage","leaves"],
    ["feuilles? de figuier","fig leaves"],
    ["feuille","leaved"],
    ["feuillée?s?","leaved"],
    ["feuille","leaf"],
    ["feuilles","leaves"],
    ["fichés?","fitchy"],
    ["fiertée?s?","teeth tail and fins gules"],
    ["figurée?s?","figured [with a face]"],
    ["fil","label"],
    ["filet en croix","filet cross [very narrow]"],
    ["filet","bendlet [narrow]/fishing net"],
    ["filiere","bordure [narrow]"],
    ["fitchy","fitchy"],
    ["flambante?s?","inflamed"],
    ["flambeau","torch"],
    ["flammes?","flame"],
    ["flancs?","flank"],
    ["flanchis","saltorels"],
    ["flèches?","arrow"],
    ["fleurée?s?","flory"],
    ["fleuronnée?s?","floretty"],
    ["fleurie?s?","flowered"],
    ["fleurs? de lis","fleur de lys"],
    ["fleurs?","flower"],
    ["flottante?s?","flying"],
    ["florencé","fleur-de-lys"],
    ["foi","two arms with hands clenched"],
    ["fontaine","fountain"],
    ["font","creates"],
    ["forcene","on its haunches"],
    ["force la machoire","forcing open its jaw"],
    ["force","pair of shears"],
    ["forces","pairs of shears"],
    ["foudres?","thunderbolt"],
    ["fourcehetée?s?","forked"],
    ["fourchée?s?","forked"],
    ["fourrurée?s?","fur proper"],
    ["fracassée?s?","shattered"],
    ["franc quartier","canton"],
    ["frangé","fringed"],
    ["frettée?s?","fretty"],
    ["fretty","fretty"],
    ["frette","fret"],
    ["fruite","fructed"],
    ["fruitée?s?","fructed"],
    ["furieux","rampant"],
    ["fusees?","fusil"],
    ["fuselée?s?","fusilly"],
    ["futée?s?","trunked/shafted"],
    ["futs?","trunk"],
    ["gai","without harness"],
    ["gaine","sheath [scabbard]"],
    ["galeres?","lymphad [galley]"],
    ["galopant","galloping"],
    ["ganté","gloved"],
    ["gantelée?s?", "gauntletted"],
    ["garçons?","boy"],
    ["gardes?","guard"],
    ["garnie?s?","hilt and pommell"],
    ["gerbes?","wheatsheaf"],
    ["gironne","gyronny"],
    ["girons?","gyron"],
    ["girouettée?s?","weather vane"],
    ["gironné","gyronny"],
    ["girronants","gyrons curved [like a scroll]"],
    ["gisante?s?","couchant"],
    ["glaives?","double edged sword"],
    ["glands?","acorn"],
    ["gonfanons?","gonfanon [flag held horizontally with 3 tails]"],
    ["gorgée?s?","collared"],
    ["gouffre","gurges [whirlpool]"],
    ["gousset","pairle [not open in chief]"],
    ["gouttes?","goutte [drop]"],
    ["granades? de guerres?","bombe"],
    ["grappes? de raisins","bunch of grapes"],
    ["grappins?","grapple [grapnel]"],
    ["grelée?s?","adorned with pearls"],
    ["greliers?","hunting horn [circular]"],
    ["grelots?","hawk bell"],
    ["grenades? de pomme","pomegranate"],
    ["grenades? de guerre","bombe"],
    ["grenades?","pomegranate/grenade/bombe"],
    ["griffons?","griffin"],
    ["grilles?","[of the helmet] bar"],
    ["grilletée?s?","belled"],
    ["grillets?","hawk bell"],
    ["grimpante?s?","rampant"],
    ["gringolée?s?","ending in serpent heads"],
    ["grives?","thrush"],
    ["grues?","crane"],
    ["gueules","gules"],
    ["guidons?","flag"],
    ["guivre","snake swallowing a child"],
    ["gumenée?s?","anchor cable"],
    ["habillée?s?","dressed"],
    ["hache danoise","long [curved] handled axe"],
    ["haches?","axe"],
    ["hachemens","mantling"],
    ["halisante?s?","swallowing"],
    ["hallebardes?","halberd"],
    ["hameçons?","fish hook"],
    ["hameyde","three bars couped in pale"],
    ["hampes?","[of the flag] pole"],
    ["hanche?s?","hip"],
    ["hardie?s?","raised head and right foot"],
    ["haute","upwards"],
    ["heraldique","heraldic"],
    ["herisse","with smaller rays between"],
    ["herissons?","hedgehog"],
    ["herissonnée?s?","with hairs erect"],
    ["hermine","ermine"],
    ["hérons?","heron"],
    ["herse sarasine","portcullis"],
    ["hersée?s?","portcullis"],
    ["homme marins?","Triton"],
    ["homme","man"],
    ["houex?","hoe"],
    ["houppés?","tasselled"],
    ["huchets?","hunting horn [without bands]"],
    ["huit","eight"],
    ["hurée?s?","head [of a boar or fish]"],
    ["immortalite","fire [from which the phoenix rises]"],
    ["inscrit","inscribed with"],
    ["intérieur", "interior"],
    ["isolée?s?","separated from the base"],
    ["issante?s? de","issuant from"],
    ["issante?s?","issuant"],
    ["jambee?s?","leg"],
    ["jambons?","ham"],
    ["jaillissante","sprays and falls"],
    ["jeune?s?","young"],
    ["jumelles","bars-gemel [doubled bars]"],
    ["l aigle","an eagle"],
    ["l aile","the wing"],
    ["l antique","ancient"],
    ["l argent","the argent"],
    ["l azur","the azure"],
    ["l ecartele","the quartering"],
    ["l écu borde","the shield with a bordure"],
    ["l écu","the shield"],
    ["l homme","the man"],
    ["l or","the or"],
    ["l une? sur l autre","in pale"],
    ["le tout","all"],
    ["l[ae]s?dite?s?","the aforesaid"],
    ["dudite?s?","the aforesaid"],
    ["le?a?s?","the"],
    ["la bande","a bend"],
    ["la bordure","a bordure"],
    ["la cross","a cross"],
    ["la fasce","fess"],
    ["la pointe","the base"],
    ["la queue","the tail"],
    ["lacs d amour","love knots"],
    ["lambel","label"],
    ["lambrequins?","Mantling:"],
    ["lames?","blade"],
    ["lampassée?s?","langued"],
    ["lances? de tournois?","tournament lance"],
    ["lances?","lance"],
    ["languée?s?","langued"],
    ["larmes?","drop"],
    ["lauriers?","laurel/laurel bush"],
    ["le manche","handle"],
    ["legende","motto"],
    ["l[ea]s?quelle","which"],
    ["léopards? lionnés?","lion rampant guardant"],
    ["léopards?","lion passant guardant"],
    ["les armes","the arms of"],
    ["lettres?","letter"],
    ["leurs?","their"],
    ["levée?s?","upright/raised"],
    ["lévrier","greyhound"],
    ["lévriers","greyhounds"],
    ["lévrons?","greyhound [no collar]"],
    ["lezards?","lizard"],
    ["léopards? naturel","naturel leopard"],
    ["licornes?","unicorn"],
    ["liée?s?","tied [banded]"],
    ["lierre","ivy"],
    ["limacons?","snail"],
    ["lion léopardés?","lion passant"],
    ["lions?","lion"],
    ["lis de jardin","lily [flower]"],
    ["lisérée?s?","bordered"],
    ["listel?","ribbon"],
    ["livres?","book"],
    ["lievres?","hare"],
    ["longée?s?","attached by a line"],
    ["lorrée?s?","finned"],
    ["losange en bande","lozenges in bend"],
    ["losange en barre","lozenges in bend sinister"],
    ["losangé","lozengy"],
    ["losanges?","lozenge"],
    ["loups?","wolf"],
    ["loups? cevrier","werewolf [?]"],
    ["lunels?","cross of four crescents"],
    ["lunes?","moon [with a face]"],
    ["maclée?s?","masculy"],
    ["macles?","mascle"],
    ["maçonné?s?","masoned"],
    ["maillets?","mallet [big head small handle]"],
    ["maisons?","house"],
    ["main benissante","right hand thumb and two fingers raised"],
    ["main d aigles?","eagle's leg"],
    ["main dextre","dexter hand"],
    ["main sinister","sinister hand"],
    ["mains?","hand"],
    ["mal gironne","gyronny [of a small number]"],
    ["mal ordonnée?s?","disordered [1 2]"],
    ["manches?","sleeve"],
    ["manchettes?","cuffs"],
    ["manipules?","vestments"],
    ["mantele","mantled"],
    ["manteau","Mantling:"],
    ["marcassins?","young boar"],
    ["marchante?","walking [passant?]"],
    ["marguerites?","daisy"],
    ["marines?","having a fish tail"],
    ["marmites?","[2 handles 3 feet] cooking pot"],
    ["marque","spotted [of dice]"],
    ["marquete","body [of butterfly]"],
    ["martinets?","martlet"],
    ["marteaus?","hammer"],
    ["masquée?s?","hooded"],
    ["massacres?","stags horn and scalp"],
    ["masse a picotons","spiked mace"],
    ["masse?s? d armes","mace"],
    ["massu?es?","mace"],
    ["masurée?s?","ruined"],
    ["mâts?","mast"],
    ["maure","moor"],
    ["melusines?","mermaid in a tub"],
    ["membre d aigle","leg of an eagle"],
    ["membre de lion","leg of a lion"],
    ["membrée?s?","legged"],
    ["memes", "the same"],
    ["menuvaire?s?","vairy [of other colours]"],
    ["mer","sea"],
    ["merlettes?","martlet [without beak or feet]"],
    ["metaux","metals"],
    ["meuble","charge"],
    ["meubles","charges"],
    ["mezail","front of the helm"],
    ["mi parti","dimidiated with"],
    ["miraillée?s?","winged [of the butterfly]"],
    ["mise?s?","put/placed"],
    ["moins","without"],
    ["molettes?","mullet"],
    ["monde","orb [globe]"],
    ["monstrueux","with a human head"],
    ["mont","mount"],
    ["montée?s?","mounted"],
    ["montante?s?","horns upward"],
    ["mores?","Moor"],
    ["morailles","twitch [horse whip?]"],
    ["morceaux? de?", "lump of"],
    ["mornée?s?","unarmed and tailless"],
    ["mortaisée?s?","dovetailed"],
    ["mortiers?","mortar [dish]"],
    ["mots?","word"],
    ["mouchettée?s?","spotted"],
    ["mouchetures? d hermine","ermine tail"],
    ["mouchetures?","ermine tail"],
    ["mouton","sheep"],
    ["moutons","sheep"],
    ["mouv de","coming from"],
    ["mouv","coming/coming from"],
    ["mouvante?s?","coming"],
    ["muriers?","blackberry bush"],
    ["murs?","wall"],
    ["muguets?","lily of the valley"],
    ["nacelle","flat bottomed boat"],
    ["nageante?s?","naiant [swimming]"],
    ["naissante?s?","naissant"],
    ["navires?","ship"],
    ["nervée?s?","lined [of leaves]"],
    ["neuf","nine"],
    ["nombril","nombril"],
    ["nouée?s?","knotted"],
    ["noued","knot (bow)"],
    ["noueux","knotted"],
    ["nourrie?s?","with the lower part removed"],
    ["nu","naked"],
    ["nuagée?s?","nebuly"],
    ["nuées?","clouds"],
    ["oies?","goose"],
    ["oiseaux?","bird"],
    ["olivier","olive"],
    ["ombre de soleil","sun eclipsed"],
    ["ombrée?s?","shaded"],
    ["ombrelle","pavilion"],
    ["onces?","snow leopard"],
    ["ondée?s?","undy"],
    ["ondoyante?s?","undulating"],
    ["ondy","wavy"],
    ["ongle","claw"],
    ["ongles","claws/talons"],
    ["onglée?s?","unguled"],
    ["opposée?s?","opposing"],
    ["or","or"],
    ["orange","tenne"],
    ["oreillée?s?","ears"],
    ["ornée?s?","decorated"],
    ["ou","(alternatively)"],
    ["ours","bear"],
    ["ouverte?s?","open/doorways"],
    ["ouvertures?","openings"],
    ["ovalée?s?","oval"],
    ["p[ae]nneton","head of the key"],
    ["paillée?s?","diapered"],
    ["pairle","pall"],
    ["paissante?s?","feeding"],
    ["pal[ey]","paly"],
    ["palisse","paly sharpened/palisade"],
    ["palmes?","palm branch"],
    ["palmier","palm tree"],
    ["palmiers","palm trees"],
    ["palé","paly"],
    ["pals?","palets"],
    ["pamée?s?","with open mouth"],
    ["pamprée?s?","leaved"],
    ["pamprepabouts","tips/ends"],
    ["pan de mur","tower wall"],
    ["panachée?s?","plumed"],
    ["panache","plume"],
    ["panaches","plumes"],
    ["panelle","poplar leaf"],
    ["panelles","poplar leaves"],
    ["pannes?","fur"],
    ["pantheres?","panther"],
    ["paons?","peacock"],
    ["papegays?","parrot"],
    ["papelonne","papellone"],
    ["par","by"],
    ["parée?s?","clothed [dressed]"],
    ["pareill?e?s?","similar"],
    ["pareillement","likewise"],
    ["parti émanchée?s?","per pale dancetty [big]"],
    ["parti","per pale"],
    ["partition","partition"],
    ["passante?s?","passant"],
    ["passée?s?","placed"],
    ["patt?ée?s?","pattee"],
    ["patenotre","prayer beads"],
    ["pattée? dextre","dexter paw"],
    ["pattée? senestre","sinister paw"],
    ["pattes?","paws"],
    ["pavillons?","flag"],
    ["pavillonnés?","the opening (of the horn)"],
    ["peautrée?s?","with tails of"],
    ["pelerins?","pilgrim"],
    ["pélicans?","pelican"],
    ["penchée?s?","bendwise [of mallets]"],
    ["pennons?","small triangular flag"],
    ["pentalphes?","pentalpha [pentagram]"],
    ["pêcheur","fisherman"],
    ["percée?s?","pierced"],
    ["perchée?s?","perched"],
    ["péri en bande","bendwise"],
    ["péri en barre","bendwise sinister"],
    ["peuplier","poplar tree"],
    ["perles?","pearl"],
    ["petite?s?","young"],
    ["phéons?","[arrow head] pheon"],
    ["phoenix","phoenix"],
    ["pics?", "peak"],
    ["picotons?","spikes"],
    ["pièces","pieces"],
    ["pied","foot"],
    ["pieds","feet"],
    ["piétée?s?","piety"],
    ["pierres?","stones/jewels"],
    ["pignates?","[small] jug"],
    ["pignon","heap of stones in base"],
    ["pignonne","battled embattled"],
    ["pile","pile"],
    ["pins?","pine tree"],
    ["piques?","pike [weapon]"],
    ["plaine","base [half depth]"],
    ["plantée?s?","planted"],
    ["plein","plain [uncharged]"],
    ["plie en round","in a circle"],
    ["pliée?s?","folded [closed]"],
    ["plume de paon","peacock feather"],
    ["plumes d autruche","ostrich feathers"],
    ["plume d autruche","ostrich feather"],
    ["plumes de paon","peacock feathers"],
    ["plumes? de heron","heron feathers"],
    ["plumes? à écrire","quill pens"],
    ["plumes?","feather"],
    ["plus elevée?s?","higher"],
    ["poignards?","dagger"],
    ["point d honneur","honour point"],
    ["point du chef","chief point"],
    ["point","point/base"],
    ["pointe","base/point"],
    ["pointes","points"],
    ["pointu","pointed"],
    ["poissons","fishes"],
    ["poisson","fish"],
    ["poitrine","stomach"],
    ["pommetée?s?","pommety"],
    ["pommes? de grenade","pomegranate"],
    ["pommes? de pin","pine cone"],
    ["ponts?","bridge"],
    ["portante?s?","carrying"],
    ["portillée?s?","gated"],
    ["posée?s?","placed"],
    ["potence","potent [or potenty]"],
    ["pourpre","purpure"],
    ["précédentes","previous"],
    ["pré","meadow"],
    ["prés de","near to"],
    ["premiere?","first"],
    ["proboscides?","proboscides"],
    ["prusse","Prussia"],
    ["purpure","purpure"],
    ["quatorze","fourteen"],
    ["quartiers?","quarter"],
    ["quatre","four"],
    ["quatrefeuille","quatrefoil"],
    ["quatrefeuilles","quatrefoils"],
    ["queues? fourchees?","with forked tail"],
    ["queues?","tail"],
    ["quintefeuilles?","cinquefoil"],
    ["qui","which"],
    ["rabate?s?","flaps [cuffs]"],
    ["rais","rays"],
    ["ramé","attired"],
    ["rameau d laurier","laurel branch"],
    ["rameau d olivier","olive branch"],
    ["rames","branched"],
    ["rampante?s?","rampant"],
    ["rameaux?","branch"],
    ["rangée?s?","arranged"],
    ["rangs?","row"],
    ["rangiers?","reaping hook"],
    ["ravissante?s?","devouring (holding in its mouth)"],
    ["rayonnant","rayonny"],
    ["rayonne","rayonny"],
    ["rayons?","spoke"],
    ["re tranche","again per bend"],
    ["rebrassée?s?","turned back [of cuffs etc.]"],
    ["recercelée?s?","recircled [more convolutions]"],
    ["recoupse?s?","also per fess"],
    ["recroisett?ées?","crosslets"],
    ["redortée?s?","bent into an oval/bent into saltire"],
    ["refente","space between petals"],
    ["regardante?s?","reguardant"],
    ["reliée?s?","bound"],
    ["remplie?s?","voided"],
    ["renard","fox [tail pendent]"],
    ["renards","foxes [tails pendent]"],
    ["renchiers?","deer"],
    ["rencontre de boeufs?","head and shoulders of an ox"],
    ["rencontré?e?s?","affronty/head affronty"],
    ["renversée?s?","reversed"],
    ["reparti","also per pale"],
    ["retournée?s?","turned backward"],
    ["retrait","touch only [one edge]"],
    ["retroussée?s?","turned up"],
    ["revetu","wearing"],
    ["rinceau","palm branch"],
    ["rivieres?","river"],
    ["rochers?","rock"],
    ["rocheuse","rocky"],
    ["robe","dress"],
    ["roc d echiquier","chess rook"],
    ["roc","head of a jousting spear"],
    ["rompue?s?","rompu [broken]"],
    ["ronde?s?","round/circular"],
    ["roses?","rose"],
    ["roseaux?","reeds"],
    ["rosiers?","rose bush"],
    ["rouant","in its pride"],
    ["roue de st.? catherine","catherine wheel"],
    ["roues?","wheel"],
    ["rubans?","ribbon"],
    ["rubis","rubies"],
    ["ruches?","bee hive"],
    ["rustr?es","rustre"],
    ["s'elevant","raised above/raised over"],
    ["sa","its/his/her"],
    ["sauf que","except that"],
    ["sable","sable"],
    ["sabres?","sabre"],
    ["saffres?","osprey"],
    ["saillante?s?","saillant [leaping forward]"],
    ["sanglée?s?","banded"],
    ["sangliers?","wild boar"],
    ["sans","without"],
    ["sapins?","fir tree"],
    ["sautoir","saltire"],
    ["sauvages?","savage"],
    ["sceptres?","sceptre"],
    ["seconde?","second"],
    ["seize","sixteen"],
    ["sellée?s?","saddled"],
    ["semé","seme"],
    ["senestre","sinister"],
    ["senestrée?s?","having to the sinister"],
    ["senestrochère","left arm"],
    ["sens","direction"],
    ["sept","seven"],
    ["serpents?","snake"],
    ["serre","talon"],
    ["seule?","single"],
    ["ses","its"],
    ["sillonée?s?","cut across by"],
    ["sinople","vert"],
    ["sirenes?","mermaid"],
    ["six","six"],
    ["soc de charrue","plough share"],
    ["soleils?","sun"],
    ["sommée?s?","surmounted by/towered"],
    ["sommets?","tip"],
    ["son","its/his/hers"],
    ["sortante?s?","coming out"],
    ["sous","under"],
    ["soutenue?s?","supported by/standing on"],
    ["soutenante?s?", "supporting"],
    ["sphinx","sphinx"],
    ["str?angues?","shank"],
    ["suspendue?s?","suspended from"],
    ["supportante?s?","supporting"],
    ["supp(orts)?","Supporters"],
    ["sur le tout","overall/on an escutcheon"],
    ["sur un tertre","on a hillock"],
    ["sur une terrasse","on a mount"],
    ["sur","over/on"],
    ["surtout","above"],
    ["surch de","surcharged with"],
    ["surch","surcharged/surcharged with"],
    ["surmontante?s?","surmounted by"],
    ["surmontée?s?","surmounted by"],
    ["tachetée?s?","spotted"],
    ["taf","tau"],
    ["taillée?s?","per bend sinister/bendwise sinister"],
    ["tare","placed [of a helmet]"],
    ["targes?","small round shields"],
    ["taureaux?","bull"],
    ["tau","tau"],
    ["tenant de","holding in"],
    ["tenant","holding"],
    ["tertres?","hillock"],
    ["tenants","Supporters:"],
    ["tendue?s?","taut"],
    ["terrasse","mount"],
    ["terrassée?s?","on a mount"],
    ["tête d argus","head of Argus"],
    ["tête de gerion","head of three faces"],
    ["tête de janus","head of Janus"],
    ["tête de meduse","head of the Gorgon"],
    ["tête de midas","head of Midas"],
    ["tête","head"],
    ["têtes de coq","cockerel heads"],
    ["têtes? de dragon","dragon's head"],
    ["têtes? de léopard","leopard's head"],
    ["têtes","heads"],
    ["tient","holding"],
    ["tiercefeuilles","trefoils"],
    ["tiercée?s?","tierced [tripled]"],
    ["tigée?s?","stemmed"],
    ["tiges?","stem"],
    ["tigers?","tiger"],
    ["tilleuls?","lime tree"],
    ["timbre","the achievements being"],
    ["tires?","line"],
    ["toisons?","fleece"],
    ["toit","roof"],
    ["toques?","cap"],
    ["tortil","wreath"],
    ["tortillée?s?","wreathed"],
    ["tours?","tower"],
    ["touchante?s?","touching"],
    ["tous deux","both"],
    ["tours? carrees?","square tower"],
    ["tourelle?s","turret"],
    ["tournée?s?","turned/reversed"],
    ["tourteau","roundel"],
    ["tourteaux","roundels"],
    ["toutes","all"],
    ["tout deux","both"],
    ["trabes?","beam [of an anchor]"],
    ["traits?","line"],
    ["tranchée?s?","per bend"],
    ["trangles","tripled"],
    ["trecheur","tressure"],
    ["trefles?","trefoil"],
    ['trèflé?e?s?',"trefle"],
    ["treillis","trellis"],
    ["treillisse","trellised"],
    ["triangles?","triangle"],
    ["tricorne","tricorn hat"],
    ["trois casques couronnés","Crowned with three helmets"],
    ["trois","three"],
    ["trompes","horns [in crest]"],
    ["trompette","horn [in crest]"],
    ["tronconnée?s?","broken into fragments"],
    ["troncs?","log/tree trunk"],
    ["tubes? de canon","cannon barrel"],
    ["tuniques?","tunic"],
    ["tuplipes?","tulip"],
    ["une?","{article}"],
    ["vaches?","cow"],
    ["vair en pale","vair in pale"],
    ["vair onde","vair undy"],
    ["vair","vair"],
    ["vairés?","vairy"],
    ["vaisseaux?","three masted ship"],
    ["vannets?","escallops showing the inside"],
    ["vase","vase"],
    ["vergettes?","palet"],
    ["versée?s?","inverted"],
    ["vertenelle","hinge [of gate]"],
    ["vers? a soie","silkworm"],
    ["vers l abîme","towards the centre"],
    ["vers?","towards"],
    ["vetu en ovale","bordure leaving an oval shape"],
    ["vetu en rond","bordure leaving a circle shape"],
    ["vetu","dressed/chape chausse  [division top centre to dex & sin base]"],
    ["vidée?s?","voided"],
    ["vieillard","old man"],
    ["vigilance","vigilance"],
    ["vilene","virile parts"],
    ["vires","annulets one within the other"],
    ["virolée?s?","bands [encircling the horn]"],
    ["visières?","visor"],
    ["vivrée?s?","[right angled] dancetty"],
    ["voguante?s?","sailling"],
    ["voiles?","veil"],
    ["vol","pair of wings"],
    ["volante?s?","flying"],
    ["volet","helmet mantling"],
    ["voutée?s?","arched"],
    ["vu de biais","in trian aspect [in perspective]"],
    ];
