var normalisationsEs = [
    ["\\-",' '],
    [";"," "],
    [":"," "],
    [","," "],
    ["\\."," "],
];

var lexiconEs = [
// The main colours & furs
           [ "de gules", "gules" ],
           [ "de sable", "sable" ],
           [ "de sinople", "vert"],
           [ "de plata", "argent"],
           [ "de argén", "argent"],
           [ "de azur", "azure"],
           [ "de sangre", "de sang (gules)"],
           [ "en gules", "gules" ],
           [ "en sable", "sable" ],
           [ "en sinople", "vert"],
           [ "en plata", "argent"],
           [ "en argén", "argent"],
           [ "en azur", "azure"],
           [ "gules", "gules" ],
           [ "sable", "sable" ],
           [ "blanco", "white" ],
           [ "sinople", "vert"],
           [ "plata", "argent"],
           [ "pla", "argent(?)"],
           [ "argén", "argent"],
           [ "azur", "azure"],
           [ "oro", "or"],
           [ "armiños", "ermine"],
           [ "veros", "vair"],
           [ "carnación", "carnation"],
           [ "cenizo", "cendree"],
           [ "contraarmiños", "cendree"],
           [ "morado", "murrey"],
           [ "natural", "proper"],
           [ "anaranjado", "orange"],
           [ "sanguíneo", "sanguine"],
           [ "leonado", "tenne"],
           [ "contraveros", "counter-vair"],
           [ "cortado en dos", "per fess"],
           [ "partido en dos", "per pale"],
           [ "en banda", "per bend sinister"],
           [ "en barra", "per bend"],
           [ "cuartelado", "quarterly"],
           [ "cuartelado con escusón", "quarterly with an inescutcheon"],


        // conjunctions, prepositions etc.
           [ "del mismo", "of the same" ],
           [ "en aspa", "in saltire" ],
           [ "en accion", "in the act of" ],
           [ "al timbre", "the crest" ],
           [ "y", "and" ],
           [ "es", "is" ],
           [ "de", "of" ],
           [ "con", "with" ],
           [ "sin", "without" ],
           [ "una", "a" ],
           [ "uno", "a" ],
           [ "un", "a" ],
           ["en", "in"],
           ["desu", "from his/its"],
           ["al", "to"],
           ["ala", "to"],
           ["por", "for/to/at"],
           ["la", "the"],
           ["del", "of the"],
           ["lo", "the"],
           ["las", "the"],
           ["les", "them"],
           ["los", "the"],
           ["el", "the"],
           ["a", "to/at/of"],
           [ "su", "its" ],
           [ "todo", "all" ],
           [ "mismo", "same" ],
           [ "que", "that" ],
           [ "esta", "this" ],
           [ "este", "this" ],
           [ "también", "also" ],
           [ "sobre", "on" ],
           [ "sus", "their" ],
           [ "entre", "between" ],
           [ "otro", "other" ],
           [ "otra", "other" ],
           [ "cada", "each/every" ],
           [ "ella", "she/her" ],
           [ "ellas", "they/them" ],
           [ "algunos", "some/a few" ],

        // ordinal numbers (other than one)
           [ "dos", "two" ],
           [ "tres", "three" ],
           [ "cuatro", "four" ],
           [ "cinco", "five" ],
           [ "seis", "six" ],
           [ "seize", "seven" ],
           [ "ocho", "eight" ],
           [ "nueve", "nine" ],
           [ "diez", "ten" ],
           [ "once", "eleven" ],
           [ "doce", "twelve" ],

        // cardinal numbers
            ["1.°", "first"],
            ["2.°", "second"],
            ["3.°", "third"],
            ["4.°", "fourth"],
            ["1°", "first"],
            ["2°", "second"],
            ["3°", "third"],
            ["4°", "fourth"],


            // heraldic terms

           [ "empinado al tronco", "against the trunk" ],
           [ "color", "colour" ],
           [ "lazo de amor", "love-knot" ],
           [ "merleta", "merlette" ],
           [ "tronco", "trunk" ],
           [ "arbol", "tree" ],
           [ "arboles", "tree" ],
           [ "puestas", "placed" ],
           [ "puesta", "placed" ],
           [ "aspas", "blades" ],
           [ "aspa", "blade" ],
           [ "estrella", "mullet" ],
           [ "estrellas", "mullets" ],
           [ "cruz latina", "latin cross" ],
           [ "cruz", "cross" ],
           [ "pie", "foot" ],
           [ "banda", "bend" ],
           [ "bandas", "bends" ],
           [ "barra", "barr" ],
           [ "fajas", "fess" ],
           [ "castillo", "castle" ],
           [ "castillos", "castles" ],
           [ "rampante", "rampant" ],
           [ "puestos", "palets" ],
           [ "lobos", "wolves" ],
           [ "lobo", "wolf" ],
           [ "jefe", "chief" ],
           [ "panelas", "quarters/pieces" ],
           [ "cortado", "couped" ],
           [ "metal", "metal" ],
           [ "punta", "point" ],
           [ "puntas", "points" ],
           [ "cargada de", "charged with" ],
           [ "cargado de", "charged with" ],
           [ "cargado", "charged" ],
           [ "mano", "hand" ],
           [ "jabali", "boar" ],
           [ "jabalis", "boars" ],
           [ "espada", "sword" ],
           [ "venera", "escallop" ],
           [ "veneras", "escallops" ],
           [ "flores de lis", "fleur-de-lys" ],
           [ "flor de lis", "fleur-de-lys" ],
           [ "armado", "armed" ],
           [ "acompafiada", "accompanied" ],
           [ "acompaffiada", "accompanied" ],
           [ "acompafiado", "accompanied" ],
           [ "acompañado", "accompanied" ],
           [ "acompanada", "accompanied" ],
           [ "piedra", "stone" ],
           [ "cabezas", "heads" ],
           [ "encina", "(holly) oak" ],
           [ "agua", "water" ],
           [ "roble", "oak" ],
           [ "palos", "palets" ],
           [ "colocadas", "placed" ],
           [ "cadena", "chain" ],
           [ "cadenas", "chains" ],
           [ "caldera", "cauldron" ],
           [ "calderas", "cauldrons" ],
           [ "ordenadas bien", "arranged" ],
           [ "ordenadas", "arranged" ],
           [ "creciente", "crescent" ],
           [ "crecientes", "crescents" ],
           [ "bezante", "bezant" ],
           [ "bezantes", "bezants" ],
           [ "medio", "half" ],
           [ "lado", "side" ],
           [ "escudo", "shield" ],
           [ "engolada", "engouled" ],
           [ "surmontado de", "surmounted by" ],
           [ "roeles", "rowells(?)" ],
           [ "puente", "bridge" ],
           [ "brazo", "arm" ],
           [ "torres", "towers" ],
           [ "torreón", "towers" ],
           [ "torreónes", "towers" ],
           [ "torre", "tower" ],
           [ "piezas", "pieces" ],
           [ "oso", "bear" ],
           [ "frutado", "fructed" ],
           [ "pasantes", "passant" ],
           [ "pasante", "passant" ],
           [ "diestra", "dexter" ],
           [ "diestro", "dexter" ],
           [ "rosas", "roses" ],
           [ "abajo", "lower" ],
           [ "bajo", "lower" ],
           [ "bajodo", "abased" ],
           [ "andantes", "passant" ],
           [ "andante", "passant" ],
           [ "afrontados", "affronty" ],
           [ "sumado de", "with" ],
           [ "sumado", "with" ],
           [ "puerta", "door" ],
           [ "puertas", "doors" ],
           [ "coronada", "crowned" ],
           [ "atado", "tied" ],
           [ "monte", "mount" ],
           [ "leon", "lion" ],
           [ "leones", "lion" ],
           [ "grifo", "griffin" ],
           [ "grifos", "griffins" ],
           [ "flordelisada", "floretty" ],
           [ "acostado de", "between" ],
           [ "acostada de", "between" ],
           [ "acostada", "between" ],
           [ "flanco", "side" ],
           [ "ondas de mar", "waves of the sea (wavy)" ],
           [ "ondas", "waves" ],
           [ "ondeados", "wavy" ],
           [ "lebrel", "dog (whippet)" ],
           [ "lebreles", "dogs (whippet)" ],
           [ "hombre", "man" ],
           [ "derecha", "right" ],
           [ "ondeado", "wavy" ],
           [ "cabrio", "chevron" ],
           [ "siniestro", "sinister" ],
           [ "siniestra", "sinister" ],
           [ "saliendo", "coming from" ],
           [ "ranversado", "reversed" ],
           [ "mazonado", "masoned" ],
           [ "almenado", "embattled" ],
           [ "hacia", "towards" ],
           [ "copa", "cup" ],
           [ "copas", "cups" ],
           [ "bandera", "flag" ],
           [ "alto", "upper" ],
           [ "alta", "upper" ],
           [ "aguila", "eagle" ],
           [ "aguilas", "eagle" ],
           [ "terrasado", "base" ],
           [ "campaña", "base" ],
           [ "gota", "goutte" ],
           [ "gotas", "gouttes" ],
           [ "perfilada", "fimbriated" ],
           [ "fileteada", "fimbriated" ],
           [ "lanza", "spear" ],
           [ "lanzas", "spears" ],
           [ "izquierda", "left" ],
           [ "centro", "centre" ],
           [ "ventanas", "windows" ],
           [ "sierpente", "serpent" ],
           [ "peleando", "fighting" ],
           [ "orla", "trimmed (garnished)" ],
           [ "moro", "Moor" ],
           [ "moros", "Moors" ],
           [ "letras", "letters" ],
           [ "hoja", "blade" ],
           [ "hojas", "blades" ],
           [ "dragon", "dragon" ],
           [ "dragones", "dragons" ],
           [ "coronado", "crowned" ],
           [ "corona", "crown" ],
           [ "coronas", "crowns" ],
           [ "arrancado", "eradicated" ],
           [ "perro", "dog" ],
           [ "perros", "dogs" ],
           [ "palomas", "doves" ],
           [ "paloma", "dove" ],
           [ "membrada", "winged" ],
           [ "guerrero", "warrior" ],
           [ "mal ordenadas", "disordered (1,2)" ],
           [ "floreteada", "floretty" ],
           [ "sumada del", "surmounted by" ],
           [ "surmontadas", "surmounted by" ],
           [ "sumada de", "surmounted by" ],
           [ "sosteniendo", "supporting" ],
           [ "sostenido", "supporting" ],
           [ "rueda", "wheel" ],
           [ "rio", "river" ],
           [ "pico", "beak/peak" ],
           [ "picos", "beaks/peaks" ],
           [ "luna", "moon" ],
           [ "lunas", "moons" ],
           [ "timbrado", "crest" ],
           [ "cuadrilongo", "rectangular" ],
           [ "campo", "field" ],
           [ "señal", "mark/seal" ],
           [ "blasón", "blazon" ],
           [ "redondeada", "rounded" ],
           [ "primero", "first" ],
           [ "segundo", "second" ],
           [ "cantones", "cantons" ],
           [ "canton", "canton" ],
           [ "cerrada", "closed" ],
           [ "aclarado", "openings" ],
           [ "aclarados", "openings" ],
           [ "aclaradas", "openings" ],
           [ "abierta", "open" ],
           [ "forma", "shape" ],
           [ "contornado", "reversed" ],
           [ "espigas", "wheat ears" ],
           [ "espiga", "wheat ear" ],
           [ "cimera", "crest" ],
           [ "acebo", "holly" ],
           [ "olivo", "olive" ],
           [ "rama", "branch" ],
           [ "lienzo", "panel" ],
           [ "recortado", "couped/(re-cut)" ],
           [ "amurallado ", "walled" ],
           [ "escudetes ", "inescutcheons" ],
           [ "escudet ", "inescutcheon" ],
           [ "soportes ", "supporters" ],
           [ "abanderado ", "bendy" ],
           [ "abarca", "surrounding" ],
           [ "abarcas", "surrounding" ],
           [ "abejas", "bees" ],
           [ "abyss", "abyss (base)" ],
           [ "actitud", "attitude" ],
           [ "garza", "heron" ],
           [ "garzas", "herons" ],
           [ "aculadas en vigilantes", "in its vigilance" ],
           [ "adiestrado", "trained" ],
           [ "alabarda", "halberd" ],
           [ "alrededor", "around" ],
           [ "anade", "duck" ],
           [ "anades", "ducks" ],
           [ "nadando", "haurient (swimming)" ],
           [ "mata", "bush" ],
           [ "matas", "bushes" ],
           [ "manzanas", "apples" ],
           [ "manzana", "apple" ],
           [ "manchado", "stained" ],
           [ "manchados", "stained" ],
           [ "manchada", "stained" ],
           [ "garra", "claw" ],
           [ "garras", "claws" ],
           [ "delante", "in front of" ],
           [ "centellean", "rayonny(?)" ],
           [ "orejas", "ears" ],
           [ "cola", "tail" ],
           [ "alas", "wings" ],
           [ "volando", "flying" ],
           [ "sola", "alone/single" ],
           [ "navarra", "Navarre" ],
           [ "ancora", "anchor" ],
           [ "arrimada", "leaning on/next to" ],
           [ "arrimadas", "leaning on/next to" ],
           [ "atravesados", "crossed" ],
           [ "aves", "birds" ],
           [ "ave", "bird" ],
           [ "azul", "blue" ],
           [ "bandado", "barry(?)" ],
           [ "caballero", "knight" ],
           [ "caballeros", "knights" ],
           [ "bordura", "bordure" ],
           [ "avellano", "avellane" ],
           [ "badajo", "bell clapper" ],
           [ "lampasados", "langued" ],
           [ "lampasado", "langued" ],
           [ "linguados", "langued (?)" ],
           [ "atraviesan", "across" ],
           [ "jaquelado", "checky" ],
           [ "jaqueladas", "checky" ],
           [ "isla", "isle" ],
           [ "losange", "lozenge" ],
           [ "muerto", "dead" ],
           [ "partido", "partition" ],
           [ "parte", "side/part" ],
           [ "negro", "negro" ],
		["situada", "placed"],
		["sostiene", "holding"],
		["superado", "above"],
		["tambores", "drums"],
		["terciado", "plywood!"],
		["terrasados", "base"],
		["terrazado", "base"],
		["torce", "torse"],
		["torno", "turned?"],
		["ufiados", "haunted?"],
		["varias", "several"],
		["vasco", "Basque?"],
		["vestido", "dressed"],
		["vibradas", "vibrated?"],
		["vierte", "pour"],
		["vuelo", "flight"],
		["vuelos", "flights"],
		["yelmo", "helmet"],
		["perseguido", "pursued"],
		["pino","pine tree"],
		["podadera", "shears"],
		["poniendo", "putting up?"],
		["primitivo", "primitive"],
		["rampantes", "rampant"],
		["ranversados", "rankled?"],
		["real", "royal?"],
		["resaltada", "highlighted?"],
		["roca", "rock"],
		["rodeandolo", "surrounding"],
		["sagrada", "sacred"],
		["santo", "holy"],
		["siete", "seven"],
		["silla", " chair"],
		["hoguera", "bonfire"],
		["jinete", "horse rider"],
		["junto", "together"],
		["lagos", "lakes"],
		["lazo", "tie"],
		["lema", "motto"],
		["levadizo", "draw?"],
		["leyenda", "legend"],
		["leén", "they read?"],
		["lugar", "place"],
		["mayor", "higher"],
		["montante", "mounted?"],
		["moviente", "moving"],
		["ojos", "eyes"],
		["otros", "others"],
		["paje", "page"],
		["palo", "stick/palet?"],
		["pante", "pant"],
		["pareadas", "paired"],
		["parra", "vine"],
		["exployada", "exploited?"],
		["faja", "fess"],
		["faro", "lighthouse"],
		["filete", "fillet"],
		["floreada", "flory"],
		["florecido", "flory"],
		["frutada", "fructed"],
		["habas", "broad beans"],
		["hay", "there is"],
		["herir", "hurt"],
		["hiere", "hurt"],
		["hierro", "iron"],
		["hierros", "irons"],
		["hinojos", "fennel"],
		["hiriendo", "hurty"],
		["cuartel", "quarter"],
		["cubierto", "covered"],
		["cules", "which"],
		["custodias", "custodians!"],
		["cuya", "whose"],
		["da", "gives"],
		["danchada", "danchado!"],
		["deba", "should!"],
		["detras", "behind"],
		["dios", "God"],
		["empinado", "steep"],
		["empinados", "steep"],
		["empufiando", "puffing!"],
		["entregar", "deliver!"],
		["era", "was"],
		["escacado", "escacado!"],
		["escaque", "escaque!"],
		["escaques", "escaques!"],
		["escudete", "escutcheon"],
		["escudetes", "escutcheons"],
		["espadas", "swords"],
		["cantonada", "cantoned"],
		["cantonado", "cantoned"],
		["cargada", "loaded"],
		["cazador", "Hunter"],
		["cebados", "primed!"],
		["collares", "collared"],
		["colmena", "hive"],
		["colocados", "placed"],
		["colocan", "place"],
		["componada", "composed"],
		["cortina", "curtain"],
		["cortinado", "curtain"],
		["cristo", "Christ"],
		["armados", "armed"],
		["arrodillado kneeling!"],
		["arrollando carrying (trailing)"],
		["asaltando attacking"],
		["asta antler/pole", ""],
		["ataca attack"],
		["atados tied up", "tied "],
		["atraillados stranded"],
		["caballo", "horse"],
		["campana", "Bell"],
		["cantaro", "pitcher"],

];

